CREATE TABLE Address(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR(255) NOT NULL,
    Area VARCHAR(255) NOT NULL,
    Address1 VARCHAR(255) NOT NULL,
    Address2 VARCHAR(255)
);
CREATE TABLE Employee(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Address_ID INT UNSIGNED NOT NULL,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255),
    Phone_Number INT UNSIGNED NOT NULL,
    LogIn_Username VARCHAR(255) NOT NULL,
    LogIn_Password VARCHAR(255) NOT NULL,
    FOREIGN KEY (Address_ID) REFERENCES Address(id)
);
CREATE TABLE Customer(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Address_ID INT UNSIGNED NOT NULL,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255),
    Phone_Number INT UNSIGNED NOT NULL,
    FOREIGN KEY (Address_ID) REFERENCES Address(id)
);
CREATE TABLE Rental(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Employee_ID INT UNSIGNED,
    Customer_ID INT UNSIGNED NOT NULL,
    RentalType VARCHAR(255) NOT NULL,
    Rental_Date DATETIME NOT NULL,
    Return_Date DATETIME NOT NULL,
    FOREIGN KEY (Employee_ID) REFERENCES Employee(id),
    FOREIGN KEY (Customer_ID) REFERENCES Customer(id)
);
CREATE TABLE Payment(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Rental_ID INT UNSIGNED NOT NULL,
    Customer_ID INT UNSIGNED NOT NULL,
    AmountDue INT UNSIGNED NOT NULL,
    Payment_Date DATETIME NOT NULL,
    FOREIGN KEY (Rental_ID) REFERENCES Rental(id),
    FOREIGN KEY (Customer_ID) REFERENCES Customer(id)
);
CREATE TABLE Car(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Brand VARCHAR(255) NOT NULL,
    Year INT UNSIGNED NOT NULL,
    Color VARCHAR(255) NOT NULL
);
CREATE TABLE Inventory(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Car_ID INT UNSIGNED NOT NULL,
    LicensePlate_Number INT UNSIGNED NOT NULL,
    RentalRate INT UNSIGNED NOT NULL,
    FOREIGN KEY (Car_ID) REFERENCES Car(id)
);
CREATE TABLE InventoryRental(
    Inventory_ID INT UNSIGNED NOT NULL,
    Rental_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (Inventory_ID, Rental_ID),
    FOREIGN KEY (Inventory_ID) REFERENCES Inventory(id),
    FOREIGN KEY (Rental_ID) REFERENCES Rental(id)
);